# Generated by Django 5.2 on 2025-08-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_airtime_announcement_cablesubscription_confirmpayment_data_deduct_depositrecord_electricitysubscript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='detail',
        ),
        migrations.AddField(
            model_name='transaction',
            name='request_id',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AddField(
            model_name='transaction',
            name='response',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AlterField(
            model_name='data',
            name='bandwidth',
            field=models.CharField(choices=[('100MB', '100MB'), ('150MB', '150MB'), ('200MB', '200MB'), ('300MB', '300MB'), ('500MB', '500MB'), ('600MB', '600MB'), ('520MB', '520MB'), ('750MB', '750MB'), ('1GB', '1GB'), ('1.5GB', '1.5GB'), ('1.8GB', '1.8GB'), ('2GB', '2GB'), ('2.5GB', '2.5GB'), ('3GB', '3GB'), ('3.2GB', '3.2GB'), ('3.9GB', '3.9GB'), ('4.5GB', '4.5GB'), ('5GB', '5GB'), ('5.2GB', '5.2GB'), ('5.9GB', '5.9GB'), ('6GB', '6GB'), ('7GB', '7GB'), ('9.2GB', '9.2GB'), ('10GB', '10GB'), ('10.8GB', '10.8GB'), ('11GB', '11GB'), ('15GB', '15GB'), ('20GB', '20GB'), ('50GB', '50GB')], max_length=15),
        ),
    ]
