# Generated by Django 5.2 on 2025-08-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transactionpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullName',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
