# Generated by Django 5.2 on 2025-08-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_profile_fullname_alter_profile_recommended_by'),
    ]

    operations = [
    ]
