# Generated by Django 5.2 on 2025-08-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20250805_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='detail',
            field=models.CharField(default='N/A', max_length=300),
        ),
    ]
