# Generated by Django 5.2 on 2025-08-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_transaction_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='request_id',
            field=models.CharField(blank=True, default='N/A', max_length=300, null=True),
        ),
    ]
