# Generated by Django 5.2 on 2025-08-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_transaction_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='response',
            field=models.CharField(blank=True, default='N/A', max_length=300, null=True),
        ),
    ]
