# Generated by Django 5.2 on 2025-08-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_transaction_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='network',
            field=models.CharField(blank=True, default='N/A', max_length=300, null=True),
        ),
    ]
