# Generated by Django 5.2 on 2025-08-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_transaction_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPinPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(choices=[('NECO', 'NECO'), ('JAMB', 'JAMB'), ('WAEC', 'WAEC'), ('NABTEB', 'NABTEB')], max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
