# Generated by Django 6.0.6 on 2026-06-18 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profile_account_generation_failed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('recipient_type', models.CharField(choices=[('all', 'All Users'), ('resellers', 'Resellers Only'), ('specific', 'Specific User')], default='all', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_count', models.PositiveIntegerField(default=0, help_text='Number of devices reached')),
                ('recipient_user', models.ForeignKey(blank=True, help_text='Required only when recipient type is "Specific User"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_notifications', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_push_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Notification',
                'verbose_name_plural': 'Push Notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
