# Generated by Django 6.0.6 on 2026-06-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_pushnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='commission_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
