# Network switches + per-plan switch. The pending DepositRecord.reference change is intentionally left out.
# Generated by Django 6.0.6 on 2026-09-17 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_network_switches(apps, schema_editor):
    NetworkStatus = apps.get_model('api', 'NetworkStatus')
    for network in ('MTN', 'AIRTEL', 'GLO', '9MOBILE'):
        NetworkStatus.objects.get_or_create(network=network, defaults={'is_enabled': True})


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_email_campaigns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Turn off to hide this plan in the app and block purchases'),
        ),
        migrations.CreateModel(
            name='NetworkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('MTN', 'MTN'), ('AIRTEL', 'Airtel'), ('GLO', 'Glo'), ('9MOBILE', '9mobile')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='On')),
                ('message', models.CharField(blank=True, help_text='Shown to customers while the network is off. Leave blank for the default message.', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Network switch',
                'verbose_name_plural': 'Network switches',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(create_network_switches, migrations.RunPython.noop),
    ]
