# Generated by Django 3.2.1 on 2023-11-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('emailAddress', models.CharField(max_length=40)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
