tv_services = (
    ('DStv Yanga', 'Dstv Yanga'),
    ('DStv Compact', 'Dstv Compact'),
    ('DStv Compact Plus', 'Dstv Compact Plus'),
    ('DStv Premium', 'Dstv Premium'),
    ('Dstv Confam', 'Dstv Confam'),
    ('Dstv Padi', 'Dstv Padi'),
    ('Dstv Asia', 'Dstv Asia'),
    ('Dstv Premium French', 'Dstv Premium French'),
    ('Dstv Premium Asia', 'Dstv Premium Asia'),
    ('Dstv Confam + ExtraView', 'Dstv Confam + ExtraView'),
    ('Dstv Yanga + ExtraView', 'Dstv Yanga + ExtraView'),
    ('Dstv Padi + ExtraView', 'Dstv Padi + ExtraView'),
    ('Dstv Compact + Extra View', 'Dstv Compact + Extra View'),
    ('Dstv Premium + Extra View', 'Dstv Premium + Extra View'),
    ('Dstv Compact Plus - Extra View', 'Dstv Compact Plus - Extra View'),
    ('Dstv HDPVR Access Service', 'Dstv HDPVR Access Service'),
    ('GOtv Max', 'GOtv Max'),
    ('GOtv Smallie', 'GOtv Smallie'),
    ('StarTimes TV', 'StarTimes TV'),
    ('MyTv', 'MyTv'),
    ('Trend TV', 'Trend TV'),
    ('Multi TV', 'Multi TV'),
    ('Daarsat', 'Daarsat')
)